# src/parser/BUILD

cc_library(
    name = "parser",
    hdrs = [
        "extended_ast.h",
    ],
    include_prefix = "parser",
    visibility = ["//visibility:public"],
    deps = [
        "//src/sql_ast:sql_ast",
        "//src/utils:utils",
    ],
)
