#ifndef SQL_PARSER_VISITOR_H
#define SQL_PARSER_VISITOR_H

#include <antlr4-runtime.h>

#include <unordered_map>
#include <vector>

#include "SqlParserBaseVisitor.h"  // Generated by ANTLR
#include "rel_ast/edb_info.h"
#include "sql_ast/sql_ast.h"

namespace rel2sql {

class SqlParserVisitor : public sql_parser::SqlParserBaseVisitor {
  /*
   * Visitor that constructs the SQL AST from parsed SQL statements.
   */
 public:
  using psr = sql_parser::SqlParser;

  SqlParserVisitor(const rel2sql::RelationMap& edb_map) : edb_map_(edb_map) {}

  virtual ~SqlParserVisitor();

  // Top-level entry point
  std::any visitStatements(psr::StatementsContext* ctx) override;

  std::any visitStatement(psr::StatementContext* ctx) override;

  // SELECT statement
  std::any visitSelect(psr::SelectContext* ctx) override;

  std::any visitSelectList(psr::SelectListContext* ctx) override;

  std::any visitSelectTerm(psr::SelectTermContext* ctx) override;

  std::any visitSelectWildcard(psr::SelectWildcardContext* ctx) override;

  std::any visitSimpleWildcard(psr::SimpleWildcardContext* ctx) override;

  std::any visitQualifiedWildcard(psr::QualifiedWildcardContext* ctx) override;

  // FROM clause
  std::any visitFrom(psr::FromContext* ctx) override;

  std::any visitTableSource(psr::TableSourceContext* ctx) override;

  std::any visitSubquerySource(psr::SubquerySourceContext* ctx) override;

  std::any visitValuesSource(psr::ValuesSourceContext* ctx) override;

  std::any visitSourceAlias(psr::SourceAliasContext* ctx) override;

  // WHERE clause
  std::any visitWhere(psr::WhereContext* ctx) override;

  // GROUP BY clause
  std::any visitGroupBy(psr::GroupByContext* ctx) override;

  // UNION
  std::any visitUnionAll(psr::UnionAllContext* ctx) override;

  std::any visitUnionSimple(psr::UnionSimpleContext* ctx) override;

  // VALUES
  std::any visitValues(psr::ValuesContext* ctx) override;

  // WITH clause
  std::any visitWith(psr::WithContext* ctx) override;

  std::any visitCte(psr::CteContext* ctx) override;

  // Conditions

  std::any visitNotCondition(psr::NotConditionContext* ctx) override;

  std::any visitAndCondition(psr::AndConditionContext* ctx) override;

  std::any visitOrCondition(psr::OrConditionContext* ctx) override;

  std::any visitComparisonCondition(psr::ComparisonConditionContext* ctx) override;

  std::any visitExistsCondition(psr::ExistsConditionContext* ctx) override;

  std::any visitInclusionCondition(psr::InclusionConditionContext* ctx) override;

  std::any visitParenCondition(psr::ParenConditionContext* ctx) override;

  std::any visitInclusion(psr::InclusionContext* ctx) override;

  // Terms (expressions)
  std::any visitConstantTerm(psr::ConstantTermContext* ctx) override;

  std::any visitColumnTerm(psr::ColumnTermContext* ctx) override;

  std::any visitFunctionTerm(psr::FunctionTermContext* ctx) override;

  std::any visitCaseTerm(psr::CaseTermContext* ctx) override;

  std::any visitMultDivTerm(psr::MultDivTermContext* ctx) override;

  std::any visitAddSubTerm(psr::AddSubTermContext* ctx) override;

  std::any visitParenTerm(psr::ParenTermContext* ctx) override;

  std::any visitSubqueryTerm(psr::SubqueryTermContext* ctx) override;

  std::any visitSimpleColumn(psr::SimpleColumnContext* ctx) override;

  std::any visitQualifiedColumn(psr::QualifiedColumnContext* ctx) override;

  std::any visitCountFunction(psr::CountFunctionContext* ctx) override;

  std::any visitSumFunction(psr::SumFunctionContext* ctx) override;

  std::any visitAvgFunction(psr::AvgFunctionContext* ctx) override;

  std::any visitMinFunction(psr::MinFunctionContext* ctx) override;

  std::any visitMaxFunction(psr::MaxFunctionContext* ctx) override;

  std::any visitCaseWhenExpr(psr::CaseWhenExprContext* ctx) override;

  std::any visitWhenClause(psr::WhenClauseContext* ctx) override;

  // Constants

  std::any visitIntConstant(psr::IntConstantContext* ctx) override;

  std::any visitFloatConstant(psr::FloatConstantContext* ctx) override;

  std::any visitStringConstant(psr::StringConstantContext* ctx) override;

  std::any visitTrueConstant(psr::TrueConstantContext* ctx) override;

  std::any visitFalseConstant(psr::FalseConstantContext* ctx) override;

  // CREATE statements
  std::any visitCreateView(psr::CreateViewContext* ctx) override;

  std::any visitCreateTable(psr::CreateTableContext* ctx) override;

 private:
  // Helper methods
  sql::ast::CompOp ParseComparisonOp(psr::ComparisonOpContext* ctx);

  sql::ast::AggregateFunction ParseAggregateFunctionName(const std::string& name);

  std::string UnquoteString(const std::string& quoted);

  std::shared_ptr<sql::ast::Source> FindSourceByAlias(const std::string& alias);

  void ResolvePendingReferences();

  struct SelectScopeFrame {
    std::unordered_map<std::string, std::shared_ptr<sql::ast::Source>> alias_map;
    std::vector<std::pair<std::shared_ptr<sql::ast::Column>, std::string>> pending_column_refs;
    std::vector<std::pair<std::shared_ptr<sql::ast::Wildcard>, std::string>> pending_wildcard_refs;
  };

  // Single stack managing per-SELECT scope state
  std::vector<SelectScopeFrame> select_stack_;
  rel2sql::RelationMap edb_map_;
};

}  // namespace rel2sql

#endif  // SQL_PARSER_VISITOR_H
