#!/usr/bin/env python3
"""Emit benchmarks/TPCH/rel/tpch_edb.edb for rel2sql's RelationMap (arity-only EDB).

Arities follow `benchmarks/TPCH/rel/tpch_schema_mapping.rel`:
  - Base entity relations `nation`, `region`, `part`, `supplier`, `customer`, `orders` are unary.
  - `partsupp` / `lineitem` are binary (composite keys).
  - Column projections from `lineitem_rel` / `partsupp_rel` are ternary (k1, k2, value).
  - Column projections from other *_rel accessors are binary (entity, value).
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MAPPING = ROOT / "benchmarks/TPCH/rel/tpch_schema_mapping.rel"
SCHEMA = ROOT / "benchmarks/TPCH/rel/tpch_schema.rel"
OUT = ROOT / "benchmarks/TPCH/rel/tpch_edb.edb"
OUT_DUCKDB_TYPES = ROOT / "benchmarks/TPCH/rel/tpch_edb_duckdb_types.edb"

# DuckDB value column (last attribute) uses VARCHAR for these TPC-H fields (string / char in tpch_schema.rel).
FIELD_TYPE_RE = re.compile(r"\(:(\w+),\s*\"(string|char)\"\)")

FUNC_RE = re.compile(r"^@function\s+def\s+(\w+)\s*\{")
DEF_RE = re.compile(r"^def\s+(\w+)\s*\(")


def string_value_relations() -> list[str]:
    """Relation names whose last EDB column holds a string (from tpch_schema.rel)."""
    names: set[str] = set()
    for m in FIELD_TYPE_RE.finditer(SCHEMA.read_text()):
        names.add(m.group(1))
    return sorted(names)


def main() -> int:
    text = MAPPING.read_text()
    names_ternary: set[str] = set()
    names_binary: set[str] = set()
    names_unary: set[str] = set()
    for line in text.splitlines():
        m = FUNC_RE.match(line.strip())
        if not m:
            continue
        name = m.group(1)
        if name.startswith("l_") or name.startswith("ps_"):
            names_ternary.add(name)
        else:
            names_binary.add(name)

    for line in text.splitlines():
        m = DEF_RE.match(line.strip())
        if not m:
            continue
        d = m.group(1)
        if d.endswith("_rel"):
            continue
        if d in {"partsupp", "lineitem"}:
            names_binary.add(d)
        elif d in {"nation", "region", "part", "supplier", "customer", "orders"}:
            names_unary.add(d)

    rows: list[tuple[str, int]] = []
    for n in sorted(names_unary):
        rows.append((n, 1))
    for n in sorted(names_binary):
        rows.append((n, 2))
    for n in sorted(names_ternary):
        rows.append((n, 3))

    lines = [
        "# Auto-generated by scripts/gen_tpch_edb.py — do not hand-edit unless you know the arities.",
        "# Consumed by: rel2sql_bin -e benchmarks/TPCH/rel/tpch_edb.edb",
        "",
    ]
    for name, ar in rows:
        lines.append(f"{name} {ar}")
    lines.append("")
    OUT.write_text("\n".join(lines))

    varchar_rels = string_value_relations()
    duckdb_lines = [
        "# Auto-generated by scripts/gen_tpch_edb.py — DuckDB DDL string columns for execute_empty.",
        "# Binary relations: A1 and A2 are VARCHAR (rel2sql uses A1 for many like_match / literal compares).",
        "# Ternary relations: A3 (value) is VARCHAR.",
        "",
    ]
    duckdb_lines.extend(varchar_rels)
    duckdb_lines.append("")
    OUT_DUCKDB_TYPES.write_text("\n".join(duckdb_lines))

    print(f"Wrote {OUT} ({len(rows)} relations)", file=sys.stderr)
    print(f"Wrote {OUT_DUCKDB_TYPES} ({len(varchar_rels)} varchar value relations)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
