#!/usr/bin/env python3
"""Generate C++ manifest table from benchmarks/TPCH/pipeline/manifest.json."""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "benchmarks/TPCH/pipeline/manifest.json"


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    manifest_path = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else MANIFEST
    out_path = (
        pathlib.Path(sys.argv[2])
        if len(sys.argv) > 2
        else manifest_path.parent / "manifest_data.h"
    )
    data = json.loads(manifest_path.read_text())
    defaults = data.get("defaults", {})
    default_timeout = int(defaults.get("timeout_sec", 60))
    default_mode = c_escape(str(defaults.get("translate_mode", "full")))
    default_unopt = bool(defaults.get("unoptimized", False))

    entries = []
    for q in sorted(data.get("queries", {}), key=lambda x: int(x)):
        e = data["queries"][q]
        unopt = e.get("unoptimized", default_unopt)
        mode = c_escape(str(e.get("translate_mode", "with_defs")))
        entries.append(
            "    QueryManifestEntry{"
            f'{q}, "{c_escape(e.get("rewrite", "ok"))}", "{c_escape(e.get("translate", "ok"))}", '
            f'"{c_escape(e.get("execute_empty", "skip"))}", "{mode}", '
            f'{int(e.get("timeout_sec", default_timeout))}, '
            f'{"true" if unopt else "false"}, '
            f'"{c_escape(e.get("stderr_contains", ""))}", "{c_escape(e.get("skip_reason", ""))}"'
            "},"
        )

    body = f"""// Generated by scripts/gen_tpch_manifest_cc.py — do not edit.

#ifndef BENCHMARKS_TPCH_PIPELINE_MANIFEST_DATA_H_
#define BENCHMARKS_TPCH_PIPELINE_MANIFEST_DATA_H_

#include <array>
#include <string_view>

namespace rel2sql::tpch_pipeline {{

struct QueryManifestEntry {{
  int query;
  std::string_view rewrite;
  std::string_view translate;
  std::string_view execute_empty;
  std::string_view translate_mode;
  int timeout_sec;
  bool unoptimized;
  std::string_view stderr_contains;
  std::string_view skip_reason;
}};

inline constexpr std::array<QueryManifestEntry, {len(entries)}> kManifestEntries = {{
{chr(10).join(entries)}
}};

}}  // namespace rel2sql::tpch_pipeline

#endif
"""
    if out_path:
        out_path.write_text(body)
    else:
        sys.stdout.write(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
