#!/usr/bin/env python3
"""Generate benchmarks/TPCH/rel/official from benchmarks/TPCH/rel/ai-rewrites.

`official/` holds the queries in the form rel2sql actually accepts: annotations
stripped, `@@N` parameters substituted, dot access rewritten, def bodies braced,
and the needed shared helpers already inlined. Nothing has to run before them --

    bazel-bin/rel2sql_bin -e benchmarks/TPCH/rel/tpch_edb.edb \
        -f benchmarks/TPCH/rel/official/6.rel

The only change beyond what scripts/tpch_rewrite.py produces is cosmetic: that
script leaves a def's body on the same line as its opening brace. Every file is
verified to translate to *byte-identical* SQL before and after that reformatting,
so `official/` cannot silently drift from the queries it was generated from.

Usage:
  scripts/tpch_official_emit.py            # regenerate all, verifying each
  scripts/tpch_official_emit.py --check    # verify only, write nothing
"""

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
AI_DIR = ROOT / "benchmarks/TPCH/rel/ai-rewrites"
OFFICIAL_DIR = ROOT / "benchmarks/TPCH/rel/official"
EDB = ROOT / "benchmarks/TPCH/rel/tpch_edb.edb"
BIN = ROOT / "bazel-bin/rel2sql_bin"

HEADER = """\
// Generated by scripts/tpch_official_emit.py from ../ai-rewrites/{q}.rel -- do not hand-edit.
// Ready for rel2sql as-is:
//   rel2sql_bin -e benchmarks/TPCH/rel/tpch_edb.edb -f benchmarks/TPCH/rel/official/{q}.rel
"""

# `def name { body` -> `def name {` + the body on its own indented line.
DEF_OPEN = re.compile(r"^(def\s+\w+\s*\{)[ \t]+(\S.*)$")


def reformat(text: str) -> str:
    out: list[str] = []
    for line in text.splitlines():
        m = DEF_OPEN.match(line)
        if m:
            out.append(m.group(1))
            out.append("    " + m.group(2))
        else:
            out.append(line)
    # collapse 3+ blank lines, and guarantee exactly one trailing newline
    return re.sub(r"\n{3,}", "\n\n", "\n".join(out)).rstrip("\n") + "\n"


def translate(rel_text: str) -> tuple[bool, str]:
    with tempfile.NamedTemporaryFile("w", suffix=".rel", delete=False) as f:
        f.write(rel_text)
        path = f.name
    try:
        p = subprocess.run(
            [str(BIN), "-e", str(EDB), "-f", path], capture_output=True, text=True, timeout=120
        )
        return p.returncode == 0, (p.stdout if p.returncode == 0 else (p.stderr or p.stdout))
    finally:
        pathlib.Path(path).unlink(missing_ok=True)


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("queries", nargs="*", type=int)
    ap.add_argument("--check", action="store_true", help="verify only, write nothing")
    a = ap.parse_args(argv)

    qs = a.queries or sorted(int(p.stem) for p in AI_DIR.glob("*.rel"))
    if not a.check:
        OFFICIAL_DIR.mkdir(parents=True, exist_ok=True)

    failures = 0
    for q in qs:
        rw = subprocess.run(
            [sys.executable, str(ROOT / "scripts/tpch_rewrite.py"), str(q), "--queries-dir", str(AI_DIR)],
            capture_output=True, text=True,
        )
        if rw.returncode != 0:
            print(f"  [FAIL] Q{q} rewrite: {rw.stderr.strip()[:160]}")
            failures += 1
            continue

        raw = rw.stdout
        pretty = HEADER.format(q=q) + "\n" + reformat(raw)

        ok_raw, sql_raw = translate(raw)
        ok_pretty, sql_pretty = translate(pretty)
        if not ok_raw:
            print(f"  [FAIL] Q{q} does not translate: {sql_raw.strip().splitlines()[:1]}")
            failures += 1
            continue
        if not ok_pretty:
            print(f"  [FAIL] Q{q} reformatting broke translation: {sql_pretty.strip().splitlines()[:1]}")
            failures += 1
            continue
        if sql_raw != sql_pretty:
            print(f"  [FAIL] Q{q} reformatting changed the generated SQL")
            failures += 1
            continue

        target = OFFICIAL_DIR / f"{q}.rel"
        if a.check:
            current = target.read_text() if target.is_file() else None
            if current != pretty:
                print(f"  [STALE] Q{q} {target.relative_to(ROOT)} differs from ai-rewrites")
                failures += 1
            else:
                print(f"  [OK]    Q{q} up to date")
        else:
            target.write_text(pretty)
            print(f"  [OK]    Q{q} -> {target.relative_to(ROOT)}")

    print()
    if failures:
        print(f"{failures} failure(s)")
        return 1
    print(f"{len(qs)} queries {'verified' if a.check else 'written'} (SQL byte-identical to ai-rewrites)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
