#include <antlr4-runtime.h>
#include <fmt/format.h>
#include <fmt/ranges.h>

#include <fstream>
// The lexer and parser are generated by ANTLR at compile time. The runtime
// headers are located in parser/generated.
#include "parser/parse.h"

int main(int argc, const char* argv[]) {
  if (argc < 2) {
    std::cerr << "Usage: " << argv[0] << " <input_file>" << std::endl;
    return 1;
  }

  std::string input_str = argv[1];

  std::ifstream input_file(input_str);

  if (!input_file) {
    throw std::runtime_error(fmt::format("Could not open file: {}", input_str));
  }

  std::ostringstream oss;

  oss << input_file.rdbuf();

  input_file.close();

  std::string input_file_str = oss.str();

  auto extended_ast = rel_parser::GetExtendedAST(input_file_str);

  std::cout << fmt::format("Root: {{{}}}", fmt::join(extended_ast.extended_data[extended_ast.root].free_variables, ","))
            << std::endl;

  return 0;
}
