#include <antlr4-runtime.h>
#include <fmt/format.h>
#include <fmt/ranges.h>

#include <fstream>

// The lexer and parser are generated by ANTLR at compile time. The runtime
// headers are located in parser/generated.
#include "parser/generated/CoreRelLexer.h"
#include "parser/generated/PrunedCoreRelParser.h"
#include "src/parser/fv_visitor.h"

int main(int argc, const char* argv[]) {
  if (argc < 2) {
    std::cerr << "Usage: " << argv[0] << " <input_file>" << std::endl;
    return 1;
  }

  std::string input_str = argv[1];

  std::ifstream input_file(input_str);

  antlr4::ANTLRInputStream input(input_file);

  rel_parser::CoreRelLexer lexer(&input);
  antlr4::CommonTokenStream tokens(&lexer);
  rel_parser::PrunedCoreRelParser parser(&tokens);

  rel_parser::PrunedCoreRelParser::ProgramContext* tree = parser.program();

  ExtendedASTVisitor visitor;

  auto extended_ast = std::any_cast<ExtendedAST>(visitor.visit(tree));

  std::cout << fmt::format("Root: {{{}}}", fmt::join(extended_ast.extended_data[extended_ast.root].free_variables, ","))
            << std::endl;

  return 0;
}
