#include "sql_parse.h"

#include "SqlLexer.h"    // Generated by ANTLR
#include "SqlParser.h"  // Generated by ANTLR
#include "error_listener.h"
#include "exceptions.h"
#include "sql_parser_visitor.h"

namespace rel2sql {

std::shared_ptr<sql::ast::Expression> ParseSQL(const std::string& sql_text) {
  auto input_stream = new antlr4::ANTLRInputStream(sql_text);
  auto lexer = new sql_parser::SqlLexer(input_stream);
  auto tokens = new antlr4::CommonTokenStream(lexer);

  auto parser = std::make_unique<sql_parser::SqlParser>(tokens);

  // Remove default error listeners and add our custom one
  parser->removeErrorListeners();
  parser->addErrorListener(new Rel2SqlErrorListener());

  auto tree = parser->statements();

  SqlParserVisitor visitor;
  auto result = visitor.visitStatements(tree);

  return std::any_cast<std::shared_ptr<sql::ast::Expression>>(result);
}

}  // namespace rel2sql
